create database institute;
use institute;

CREATE TABLE FACULTY(
FID INT,
FNAME VARCHAR(15),
LNAME VARCHAR(15),
DOB DATE,
DOJ DATE,
GENDER CHAR,
ADDRESS VARCHAR(40),
CITY VARCHAR(15),
SALARY INT,
DESIGNATION VARCHAR(10), 
PRIMARY KEY(FID)
);

CREATE TABLE DEPARTMENT(
Dno int,
Dname varchar(20),
Dloc varchar(20), 
Head_Fid integer,
PRIMARY KEY(Dno),
FOREIGN KEY(Head_Fid) references FACULTY(Fid)
);

ALTER TABLE FACULTY ADD COLUMN DNO INT;
ALTER TABLE FACULTY ADD CONSTRAINT FOREIGN KEY(DNO) REFERENCES DEPARTMENT(Dno);

CREATE TABLE STUDENT(
USN CHAR(10),
Fname varchar(15),
Lname varchar(15),
Gender char(1),
Address varchar(30),
City varchar(15),
sem int, 
cell_no char(10),
dno int,
Primary key(USN),
Foreign key(Dno) references DEPARTMENT(Dno)
);

CREATE TABLE SUBJECTS(
SUB_CODE varchar(10),
SUB_NAME VARCHAR(15),
TYPE CHAR,
CREDIT INT,
PRIMARY KEY (SUB_CODE) 
);

CREATE TABLE ENGAGES(
FID INT,
SUB_CODE VARCHAR(10),
HOURS INT,
FOREIGN KEY (SUB_CODE) REFERENCES SUBJECTS(SUB_CODE),
FOREIGN KEY(FID) REFERENCES FACULTY(FID)
);

CREATE TABLE TEST(
TEST_NO INT,
DATE DATE,
TIME TIME,
PRIMARY KEY(TEST_NO)
);

CREATE TABLE SCORE(
USN CHAR(10),
SUB_CODE VARCHAR(10),
TEST_NO INT,
I_A_MARKS INT,
FOREIGN KEY(TEST_NO) REFERENCES TEST(TEST_NO)
);

CREATE TABLE ATTENDANCE(
USN VARCHAR(10),
SUB_CODE VARCHAR(10),
DATE DATE,
TIME TIME,
STATUS VARCHAR(5),
REASON VARCHAR(20),
FOREIGN KEY (USN) REFERENCES STUDENT(USN),
FOREIGN KEY (SUB_CODE) REFERENCES SUBJECTS(SUB_CODE)
);

CREATE TABLE PARENT(
USN VARCHAR(10),
PNAME VARCHAR(15),
ADDRESS VARCHAR(30),
CITY VARCHAR(10),
PINCODE INT,
CELL_NO INT,
FOREIGN KEY(USN) REFERENCES STUDENT(USN)
);
